/*
 * Settings.cpp
 *
 *  Created on: 23 ���. 2018 �.
 *      Author: Sales
 */

#include <MC/Settings/Settings.hpp>
#include "MC/Settings/FlashDataBlock.hpp"

Settings::Settings():
perforationTime(PERFORATION_TIME_FACTORY_SETTING, PERFORATION_TIME_OFFSET),
ignitionTime(IGNITION_TIME_FACTORY_SETTING, IGNITION_TIME_OFFSET),
initialPositioningTimeout(INITIAL_POSITIONING_TIMEOUT_FACTORY_SETTING, INITIAL_POSITIONING_TIMEOUT_OFFSET),
torchUpTime(TORCH_UP_TIMEOUT_FACTORY_SETTING, TORCH_UP_TIMEOUT_OFFSET),
acceleration(ACCELERATION_FACTORY_SETTING, ACCELERATION_OFFSET),
freeRunVelocity(FREE_RUN_VELOCITY_FACTORY_SETTING, FREE_RUN_VELOCITY_OFFSET),
workingVelocity(WORKING_VELOCITY_FACTORY_SETTING, WORKING_VELOCITY_OFFSET),
autoLimitRatio(AUTO_LIMIT_RATIO_FACTORY_SETTING, AUTO_LIMIT_RATIO_OFFSET),
startVelocity(START_VELOCITY_FACTORY_SETTING, START_VELOCITY_OFFSET),
adjustmentVelocity(ADJUSTMENT_VELOCITY_FACTORY_SETTING, ADJUSTMENT_VELOCITY_OFFSET){
	this->CommitChanges();
}

Settings settings;

